# Generated by Django 4.0 on 2023-01-22 14:50

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('username', models.CharField(default='', max_length=30, verbose_name='nic name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_type', models.CharField(default='Subadmin', max_length=12)),
                ('address_line_1', models.CharField(default='', max_length=200)),
                ('address_line_2', models.CharField(default='', max_length=200)),
                ('profile_pic', models.ImageField(default='', upload_to='user/image/profile_image')),
                ('is_verified', models.BooleanField(default=False)),
                ('otp', models.CharField(default='', max_length=200)),
                ('country_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('country', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('zip_code', models.CharField(default='', max_length=100)),
                ('is_user_blocked', models.BooleanField(default=False)),
                ('timezone', models.TextField(default='UTC')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('username', models.CharField(default='', max_length=30, verbose_name='nic name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_type', models.CharField(default='Docter', max_length=12)),
                ('Education', models.CharField(default='', max_length=50)),
                ('specilist_type', models.CharField(default='', max_length=12)),
                ('address_line_1', models.CharField(default='', max_length=200)),
                ('address_line_2', models.CharField(default='', max_length=200)),
                ('profile_pic', models.ImageField(default='deafult_profile_pic.jpeg', upload_to='admin/image/profile_image')),
                ('is_verified', models.BooleanField(default=False)),
                ('otp', models.CharField(default='', max_length=200)),
                ('country_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('country', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('zip_code', models.CharField(default='', max_length=100)),
                ('is_user_blocked', models.BooleanField(default=False)),
                ('timezone', models.TextField(default='UTC')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('username', models.CharField(default='', max_length=30, verbose_name='nic name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_type', models.CharField(default='user', max_length=12)),
                ('address_line_1', models.CharField(default='', max_length=200)),
                ('address_line_2', models.CharField(default='', max_length=200)),
                ('profile_pic', models.ImageField(default='deafult_profile_pic.jpeg', upload_to='admin/image/profile_image')),
                ('is_verified', models.BooleanField(default=False)),
                ('referal_number', models.CharField(default='', max_length=200)),
                ('otp', models.CharField(default='', max_length=200)),
                ('country_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('country', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('zip_code', models.CharField(default='', max_length=100)),
                ('is_user_blocked', models.BooleanField(default=False)),
                ('timezone', models.TextField(default='UTC')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=10)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='accounts.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Admin_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=10)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='accounts.admin')),
            ],
        ),
    ]
