# Generated by Django 4.0 on 2023-01-22 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_admin_managers_alter_doctor_managers_and_more'),
        ('patient', '0002_alter_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admin',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_can_view', to='accounts.admin'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_can_view', to='accounts.user'),
        ),
    ]
